# Generated by Django 3.2.4 on 2021-08-29 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=50, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('income', models.FloatField(blank=True, default=0.0, null=True)),
                ('expense', models.FloatField(blank=True, default=0.0, null=True)),
                ('balance', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('desc', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('type1', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comp_detail')),
            ],
        ),
    ]
